import type { AnalysisResult } from "./types"

export const MOCK_RESULT: AnalysisResult = {
  scan_id: "a3f8c1d2-e4b5-4a6f-b7c8-d9e0f1a2b3c4",
  analyzed_at: "2026-02-10T14:32:00Z",
  tool_version: "0.2.0",
  filename: "suspicious_track_master.wav",
  duration_seconds: 214.7,
  sample_rate: 44100,
  channels: 2,
  peak_db: -0.3,
  rms_db: -14.2,
  overall_score: 72.4,
  confidence: "high",
  confidence_value: 0.87,
  depth_used: "deep",
  concordance_boost: true,
  watermark_detected: true,
  loudness_range_lufs: -13.4,
  high_freq_cutoff_hz: 16200,
  stereo_correlation: 0.943,
  overall_ai_likelihood: "likely",
  domain_results: [
    {
      domain: "spectral",
      display_name: "Spectral Analysis",
      score: 0.78,
      active: true,
      weight: 0.40,
      artifacts: [
        {
          name: "high_frequency_rolloff",
          detected: true,
          severity: "high",
          value: 16200,
          description: "Sharp high-frequency cutoff detected at 16.2 kHz, typical of neural vocoder output",
          probability: 0.88,
          domain: "spectral",
          weight: 1.2,
          tier: 2,
        },
        {
          name: "spectral_bandwidth_anomaly",
          detected: true,
          severity: "medium",
          value: 0.72,
          description: "Unusually narrow spectral bandwidth distribution compared to natural recordings",
          probability: 0.65,
          domain: "spectral",
          weight: 1.0,
          tier: 3,
        },
        {
          name: "harmonic_regularity",
          detected: false,
          severity: "low",
          value: 0.31,
          description: "Harmonic spacing shows minor regularity patterns but within natural variance",
          probability: 0.28,
          domain: "spectral",
          weight: 0.8,
          tier: 4,
        },
      ],
    },
    {
      domain: "structural",
      display_name: "Structural Analysis",
      score: 0.61,
      active: true,
      weight: 0.20,
      artifacts: [
        {
          name: "repetition_entropy",
          detected: true,
          severity: "medium",
          value: 0.58,
          description: "Low entropy in structural repetition suggests template-based generation",
          probability: 0.71,
          domain: "structural",
          weight: 1.0,
          tier: 3,
        },
        {
          name: "section_boundary_artifacts",
          detected: false,
          severity: "none",
          value: 0.19,
          description: "Section transitions appear natural with no abrupt boundary artifacts",
          probability: 0.15,
          domain: "structural",
          weight: 0.9,
          tier: 4,
        },
      ],
    },
    {
      domain: "vocal",
      display_name: "Vocal Analysis",
      score: 0.82,
      active: true,
      weight: 0.20,
      artifacts: [
        {
          name: "formant_regularity",
          detected: true,
          severity: "high",
          value: 0.91,
          description: "Vocal formant transitions show machine-like regularity with reduced natural variance",
          probability: 0.92,
          domain: "vocal",
          weight: 1.3,
          tier: 1,
        },
        {
          name: "breath_detection",
          detected: true,
          severity: "medium",
          value: 0.04,
          description: "Minimal breath artifacts detected; natural vocals typically show more breathing patterns",
          probability: 0.74,
          domain: "vocal",
          weight: 1.1,
          tier: 2,
        },
        {
          name: "pitch_micro_variation",
          detected: true,
          severity: "medium",
          value: 0.22,
          description: "Reduced micro-pitch variations compared to natural singing voice baseline",
          probability: 0.68,
          domain: "vocal",
          weight: 0.9,
          tier: 3,
        },
      ],
    },
    {
      domain: "temporal",
      display_name: "Temporal Analysis",
      score: 0.45,
      active: true,
      weight: 0.10,
      artifacts: [
        {
          name: "transient_sharpness",
          detected: false,
          severity: "low",
          value: 0.38,
          description: "Transient attacks are slightly softer than expected but within acceptable range",
          probability: 0.34,
          domain: "temporal",
          weight: 1.0,
          tier: 3,
        },
        {
          name: "rhythmic_quantization",
          detected: true,
          severity: "medium",
          value: 0.67,
          description: "Rhythmic timing shows high quantization precision atypical of live performance",
          probability: 0.62,
          domain: "temporal",
          weight: 0.8,
          tier: 4,
        },
      ],
    },
    {
      domain: "spatial",
      display_name: "Spatial Analysis",
      score: 0.33,
      active: true,
      weight: 0.05,
      artifacts: [
        {
          name: "stereo_correlation_anomaly",
          detected: false,
          severity: "none",
          value: 0.943,
          description: "Stereo correlation is within normal range for mixed audio content",
          probability: 0.21,
          domain: "spatial",
          weight: 1.0,
          tier: 4,
        },
        {
          name: "phase_coherence",
          detected: false,
          severity: "low",
          value: 0.87,
          description: "Phase coherence shows minor anomalies but consistent with professional mixing",
          probability: 0.29,
          domain: "spatial",
          weight: 0.7,
          tier: 4,
        },
      ],
    },
    {
      domain: "production",
      display_name: "Production Analysis",
      score: 0.52,
      active: true,
      weight: 0.05,
      artifacts: [
        {
          name: "dynamic_range_compression",
          detected: true,
          severity: "medium",
          value: 4.2,
          description: "Unusually flat dynamic range suggests synthetic mastering chain",
          probability: 0.58,
          domain: "production",
          weight: 0.9,
          tier: 3,
        },
        {
          name: "reverb_tail_analysis",
          detected: false,
          severity: "none",
          value: 0.44,
          description: "Reverb characteristics appear natural with appropriate decay profiles",
          probability: 0.18,
          domain: "production",
          weight: 0.7,
          tier: 4,
        },
      ],
    },
  ],
  ai_artifacts: [],
}

// Populate the flat ai_artifacts list from domain_results
MOCK_RESULT.ai_artifacts = MOCK_RESULT.domain_results.flatMap((d) => d.artifacts)
